version: '3'

services:
  nlp:
    image: nlp-project:latest
    build: .
    volumes:
      - "./data:/nlp/data"
      - "./data_preprocessing:/nlp/data_preprocessing"
      - "./notebooks:/nlp/notebooks"
      - "./src:/nlp/src"
    command: sleep infinity