version: '3'

services:
  advanced_ml_jupyter:
    image: nlp-project:latest
    build: .
    volumes:
      - "./data:/nlp/data"
      - "./notebooks:/nlp/notebooks"
      - "./src:/nlp/src"
    ports:
      - "8888:8888"
    command: jupyter notebook --no-browser --ip='*' --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''